import { createApp } from 'vue'
import './style.css'
import App from './App.vue'
import router from './router'

// Naive UI
import naive from 'naive-ui'

// Font Awesome
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faHome,
  faList,
  faPlus,
  faChartLine,
  faGear,
  faWallet,
  faCalendarDay,
  faCalendar,
  faChartBar,
  faMoneyBillWave,
  faArrowTrendUp,
  faArrowTrendDown,
  faBars,
  faTimes,
  faEdit,
  faTrash,
  faFilter,
  faSearch,
  faCircleCheck,
  faCircleXmark,
  faCheckCircle,
  faExclamationCircle,
  faSave,
  faXmark,
  faUtensils,
  faBus,
  faShoppingCart,
  faFilm,
  faHeartbeat,
  faGraduationCap,
  faEllipsisH,
  faBriefcase,
  faGift,
  faPiggyBank,
  faExchangeAlt,
  faMoneyBillTransfer,
  faFileInvoiceDollar,
  faReceipt,
  faArrowRight,
  faArrowLeft,
  faHome as faHouse,
  faTag,
  faTags,
  faFolderOpen,
  faDownload,
  faUpload,
  faUndo,
  faCoffee,
  faPizzaSlice,
  faWineGlass,
  faTaxi,
  faTrain,
  faPlane,
  faCar,
  faBicycle,
  faShoppingBag,
  faShirt,
  faGamepad,
  faMusic,
  faBook,
  faBolt,
  faWifi,
  faMobile,
  faDumbbell,
  faPrescriptionBottle,
  faBookOpen,
  faLaptop,
  faHandHoldingUsd,
  faHeart,
  faStar,
  faFlag,
  faImage
} from '@fortawesome/free-solid-svg-icons'

// Regular 风格图标（更细的线条）
import {
  faChartBar as farChartBar,
  faCircle as farCircle,
  faSquare as farSquare,
  faSquarePlus as farSquarePlus,
  faSquareCheck as farSquareCheck,
  faCalendar as farCalendar
} from '@fortawesome/free-regular-svg-icons'

// 添加图标到库
library.add(
  faHome,
  faList,
  faPlus,
  faChartLine,
  faGear,
  faWallet,
  faCalendarDay,
  faCalendar,
  faChartBar,
  farChartBar,
  faMoneyBillWave,
  faArrowTrendUp,
  faArrowTrendDown,
  faBars,
  faTimes,
  faEdit,
  faTrash,
  faFilter,
  faSearch,
  faCircleCheck,
  faCircleXmark,
  faCheckCircle,
  faExclamationCircle,
  faSave,
  faXmark,
  faUtensils,
  faBus,
  faShoppingCart,
  faFilm,
  faHeartbeat,
  faGraduationCap,
  faEllipsisH,
  faBriefcase,
  faGift,
  faPiggyBank,
  faExchangeAlt,
  faMoneyBillTransfer,
  faFileInvoiceDollar,
  faReceipt,
  faArrowRight,
  faArrowLeft,
  faTag,
  faTags,
  faFolderOpen,
  faDownload,
  faUpload,
  faUndo,
  faCoffee,
  faPizzaSlice,
  faWineGlass,
  faTaxi,
  faTrain,
  faPlane,
  faCar,
  faBicycle,
  faShoppingBag,
  faShirt,
  faGamepad,
  faMusic,
  faBook,
  faBolt,
  faWifi,
  faMobile,
  faDumbbell,
  faPrescriptionBottle,
  faBookOpen,
  faLaptop,
  faHandHoldingUsd,
  faHeart,
  faStar,
  faFlag,
  faImage
)

const app = createApp(App)
app.component('font-awesome-icon', FontAwesomeIcon)
app.use(router)
app.use(naive)
app.mount('#app')
